export const IATA_META: Record<string, { city: string; country: string }> = {
  // US — Southeast
  ATL: { city: 'Atlanta',          country: 'Georgia'         },
  MIA: { city: 'Miami',            country: 'Florida'         },
  FLL: { city: 'Fort Lauderdale',  country: 'Florida'         },
  TPA: { city: 'Tampa',            country: 'Florida'         },
  ORL: { city: 'Orlando',          country: 'Florida'         },
  JAX: { city: 'Jacksonville',     country: 'Florida'         },
  SAV: { city: 'Savannah',         country: 'Georgia'         },
  BHM: { city: 'Birmingham',       country: 'Alabama'         },
  BNA: { city: 'Nashville',        country: 'Tennessee'       },
  MEM: { city: 'Memphis',          country: 'Tennessee'       },
  MSY: { city: 'New Orleans',      country: 'Louisiana'       },
  // US — Northeast
  JFK: { city: 'New York',         country: 'New York'        },
  NYC: { city: 'New York',         country: 'New York'        },
  BOS: { city: 'Boston',           country: 'Massachusetts'   },
  PHL: { city: 'Philadelphia',     country: 'Pennsylvania'    },
  BWI: { city: 'Baltimore',        country: 'Maryland'        },
  WAS: { city: 'Washington DC',    country: 'DC'              },
  ORF: { city: 'Norfolk',          country: 'Virginia'        },
  RDU: { city: 'Raleigh',          country: 'North Carolina'  },
  CLT: { city: 'Charlotte',        country: 'North Carolina'  },
  CLE: { city: 'Cleveland',        country: 'Ohio'            },
  DTT: { city: 'Detroit',          country: 'Michigan'        },
  // US — Midwest
  ORD: { city: 'Chicago',          country: 'Illinois'        },
  CHI: { city: 'Chicago',          country: 'Illinois'        },
  STL: { city: 'St. Louis',        country: 'Missouri'        },
  MSP: { city: 'Minneapolis',      country: 'Minnesota'       },
  // US — South / Texas
  DFW: { city: 'Dallas',           country: 'Texas'           },
  IAH: { city: 'Houston',          country: 'Texas'           },
  HOU: { city: 'Houston',          country: 'Texas'           },
  SAT: { city: 'San Antonio',      country: 'Texas'           },
  AUS: { city: 'Austin',           country: 'Texas'           },
  // US — West
  LAX: { city: 'Los Angeles',      country: 'California'      },
  SFO: { city: 'San Francisco',    country: 'California'      },
  SEA: { city: 'Seattle',          country: 'Washington'      },
  DEN: { city: 'Denver',           country: 'Colorado'        },
  PHX: { city: 'Phoenix',          country: 'Arizona'         },
  LAS: { city: 'Las Vegas',        country: 'Nevada'          },
  // Canada
  YVR: { city: 'Vancouver',        country: 'Canada'          },
  YTO: { city: 'Toronto',          country: 'Canada'          },
  YMQ: { city: 'Montreal',         country: 'Canada'          },
  YEA: { city: 'Edmonton',         country: 'Canada'          },
  YYC: { city: 'Calgary',          country: 'Canada'          },
  // Mexico
  MEX: { city: 'Mexico City',      country: 'Mexico'          },
  CUN: { city: 'Cancún',           country: 'Mexico'          },
  GDL: { city: 'Guadalajara',      country: 'Mexico'          },
  // Caribbean
  SJU: { city: 'San Juan',         country: 'Puerto Rico'     },
  BQN: { city: 'Aguadilla',        country: 'Puerto Rico'     },
  MBJ: { city: 'Montego Bay',      country: 'Jamaica'         },
  KIN: { city: 'Kingston',         country: 'Jamaica'         },
  NAS: { city: 'Nassau',           country: 'Bahamas'         },
  PUJ: { city: 'Punta Cana',       country: 'Dominican Republic' },
  SDQ: { city: 'Santo Domingo',    country: 'Dominican Republic' },
  AUA: { city: 'Aruba',            country: 'Aruba'           },
  STT: { city: 'St. Thomas',       country: 'USVI'            },
  SLU: { city: 'St. Lucia',        country: 'Caribbean'       },
  ANU: { city: 'Antigua',          country: 'Caribbean'       },
  POS: { city: 'Port of Spain',    country: 'Trinidad'        },
  HAV: { city: 'Havana',           country: 'Cuba'            },
  // Central America
  GUA: { city: 'Guatemala City',   country: 'Guatemala'       },
  SJO: { city: 'San José',         country: 'Costa Rica'      },
  PTY: { city: 'Panama City',      country: 'Panama'          },
  SAL: { city: 'San Salvador',     country: 'El Salvador'     },
  MGA: { city: 'Managua',          country: 'Nicaragua'       },
  // South America
  BOG: { city: 'Bogotá',           country: 'Colombia'        },
  MDE: { city: 'Medellín',         country: 'Colombia'        },
  CTG: { city: 'Cartagena',        country: 'Colombia'        },
  LIM: { city: 'Lima',             country: 'Peru'            },
  GRU: { city: 'São Paulo',        country: 'Brazil'          },
  SAO: { city: 'São Paulo',        country: 'Brazil'          },
  RIO: { city: 'Rio de Janeiro',   country: 'Brazil'          },
  SCL: { city: 'Santiago',         country: 'Chile'           },
  BUE: { city: 'Buenos Aires',     country: 'Argentina'       },
  // Europe
  LHR: { city: 'London',           country: 'England'         },
  CDG: { city: 'Paris',            country: 'France'          },
  AMS: { city: 'Amsterdam',        country: 'Netherlands'     },
  FRA: { city: 'Frankfurt',        country: 'Germany'         },
  MAD: { city: 'Madrid',           country: 'Spain'           },
  BCN: { city: 'Barcelona',        country: 'Spain'           },
  FCO: { city: 'Rome',             country: 'Italy'           },
  MIL: { city: 'Milan',            country: 'Italy'           },
  LIS: { city: 'Lisbon',           country: 'Portugal'        },
  ATH: { city: 'Athens',           country: 'Greece'          },
  IST: { city: 'Istanbul',         country: 'Turkey'          },
  // Middle East / Asia
  DXB: { city: 'Dubai',            country: 'UAE'             },
  NRT: { city: 'Tokyo',            country: 'Japan'           },
  TYO: { city: 'Tokyo',            country: 'Japan'           },
  BKK: { city: 'Bangkok',          country: 'Thailand'        },
  SIN: { city: 'Singapore',        country: 'Singapore'       },
  HKG: { city: 'Hong Kong',        country: 'Hong Kong'       },
  // Oceania
  SYD: { city: 'Sydney',           country: 'Australia'       },
}
